name: dot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  hive: ^2.2.3
  intl: ^0.19.0
  flutter_phoenix: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/dot.jpeg